package com.release.plexigo.models

data class Contentdetail(
    val blockMessage: String,
    val castCrew: ArrayList<CastModel>,
    val censorrating: String,
    val channelID: String,
    val contentType: String,
    val contentid: Int,
    val contentname: String,
    val country: String,
    val dashURL: Any,
    val duration: String,
    val fairplayCertificateURL: Any ?= null,
    val fairplayLicenseURL: Any?= null,
    val genere: String,
    val hlsURL: Any ?= null,
    val imagepath: String,
    val inr: String,
    val isBrowserBlock: String,
    val isDRMContent: String,
    val isFavourite: String,
    val isFilmFestival: String,
    val isLive: String,
    val isLiveDRM: Any ?= null,
    val isQnAEnabled: String,
    val isWatchLater: String,
    val language: String,
    val languages: ArrayList<LanguageModel>,
    val ottPlatforms: List<OTTModel>,
    val paymentGateway: List<PaymentGateway>,
    val pollInterval: String,
    val posterpath: String,
    val ppv: String,
    val ppvTitle: String,
    val ppvType: String,
    val ppvValidity: Int,
    val rating: String,
    val releaseyear: String,
    val rentValidity: String,
    val seasons: List<TvSeriesSeasons>,
    val showLikes: String,
    val synopsis: String,
    val tacLink: String,
    val tacText: String,
    val trailerpath: Any ?= null,
    val usd: String,
    val userLikes: Int,
    val videopath: Any? = null,
    val watchDuration: String,
    val wideimgepath: Any? = null,
    val widevineLicenseURL: Any,
    val thumbnailText : String? = null,
    val contentExpiryTime : String? = null
)